### ISSUE TITLE
Awards & User Weight Units

### ISSUE THREAD

**Issue by FitAbleFitness** [alicolville/Weight-Tracker#522]
Hi Ali,

The weight unit it is already user preference and I have noticed if changed after using the default e.g. pounds to kg the units will display correctly on the frontend. Also the preferences show this change to the user.

However, the preferences on the admin side do not change and nor do the entries display in the new chosen format.

Now the real reason I'm here :).

I have users that wish to stay with the pounds, stones/pounds and some that wish to use Kg's. Is it possible to have different awards based on the users preferences? So those using pounds would get awards when hitting pound targets and Kg users getting awards when hitting their Kg targets?

Thank you.

**Comment by alicolville** [comment]
Hello there,

Yes, the first part is by design :) Most admins want the weight units to be consistent rather than changing between user records in the admin area

I'm afraid at the moment there isn't a way with the awards to do that (bar a % lost) but something I could look at for a future release.

Cheers,

Ali
