### ISSUE TITLE
WP plugin repository closure? 

### ISSUE THREAD

**Issue by lbdsgn** [alicolville/Weight-Tracker#606]
What happened with weight tracker and meal tracker closure and review? Are you OK?

**Comment by alicolville** [comment]
Oh weird! No notification from them!!

Looking into it!

**Comment by lbdsgn** [comment]
Thank you!

**Comment by sbservices** [comment]
Hope all is well Ali. Good luck with the recoding. 🙏

**Comment by alicolville** [comment]
Thanks folks - I've decided to just leave wordpress.org - complete pain! 

That said, can all be downloaded on here and also http://weighttracker.yeken.uk

I'm also looking into automatic updates via WP plugins page :)

**Comment by sbservices** [comment]
Where are the instructions for updating the plugin now that its not coming from the Wordpress portal?  Do we just upload the newly downloaded version and overwrite current one?  I haven't done any updates since you had to exit stage left!!  I was waiting to see if you were going to get the automatic updates thing working. I can test on a staging site in any case, but thought I'd ask in case there are further developments since Sept last year.

**Comment by alicolville** [comment]
The latest versions of the plugin should still update automatically, but just grab the zip file from my servers instead of the WP site.

I also still push the latest updates to the [WP repo](https://wordpress.org/plugins/weight-loss-tracker/), as people can still update from it, just not download if the first time. So auto updates should just work :)

**Comment by sbservices** [comment]
It wasn't showing that there was an update available here, so I thought we were on the latest version, but then remembered the repository closure issue, so I thought I'd check on your documentation and found there were loads of updates!!! 

<img width="1136" alt="Image" src="https://github.com/user-attachments/assets/5109cd92-82da-44d7-a98c-79ea702a22f0" />

**Comment by sbservices** [comment]
shall I 'enable auto-update' on the plugin?

**Comment by alicolville** [comment]
Yeah, I do :)
