### ISSUE TITLE
Add ability for users to modify Macronutrient calculator

### ISSUE THREAD

**Issue by alicolville** [alicolville/Weight-Tracker#97]
Allow them to:

- Split % when calculating macronutrients
- Specify number of calories to subtract for weight loss
- Add option to state that admins can override calorie subtract and caps per user
- Add option to state whether or not a user can edit their own

**Comment by worldsdream** [comment]
We are not able to make our own macros? That is a must. Please make this happen.

**Comment by yekenuk** [comment]
Currently no...

**Comment by worldsdream** [comment]
When we calculate the macros. We need to have an option for manual(that we can adjust). This needs to be done before the food tracking https://github.com/yekenuk/Weight-Loss-Tracker/issues/175. Because we need to adjust the macros at our own ratio. Then calculate the food after.

Keep it up champion.

**Comment by alicolville** [comment]
Done in 7.6
